version: "3"
services:
  flask_test:
    image: yxhpy520/open-proxy-ai:20240422075632
    restart: always # 总是重启
    container_name: open-proxy-ai_v1.0 # 运行后的容器的名称
    ports:
      - "5000:5000" # 端口映射， 这里是将 docker 容器内的 80 端口映射到云服务器的 5500 端口
    volumes:
      - ./config:/app/config