name: CI/CD to Heroku

on:
  push:
    branches:
      - master # 触发工作流程的分支,可以根据需要修改

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/open-proxy-ai:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/open-proxy-ai:${{ github.sha }}