name: CI/CD to Heroku

on:
  push:
    branches:
      - master # 触发工作流程的分支,可以根据需要修改

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Generate unique version tag # 生成唯一版本标签
        id: version
        run: echo "::set-output name=new_tag::$(date +'%Y%m%d%H%M%S')"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/open-proxy-ai:${{ steps.version.outputs.new_tag }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/open-proxy-ai:${{ steps.version.outputs.new_tag }}

  deploy-to-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update docker-compose.yml with new version # 更新 docker-compose.yml 中的版本
        run: |
          sed -i 's|${{ secrets.DOCKER_HUB_USERNAME }}/open-proxy-ai:latest|${{ secrets.DOCKER_HUB_USERNAME }}/open-proxy-ai:${{ steps.version.outputs.new_tag }}|g' docker-compose.yml

      - name: Copy Docker Compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: './docker-compose.yml'
          target: '/srv/open-proxy-ai'

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            cd /srv/open-proxy-ai
            docker-compose pull
            docker-compose up -d