name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environment variables
        env:
          FLASK_APP: "app.py"
          FLASK_ENV: "development"
          FLASK_DEBUG: "0"
        run: |
          echo $FLASK_APP
          echo $FLASK_ENV
          echo $FLASK_DEBUG
      - name: Build and deploy
        run: |
          nohup python3 -m flask run &  

